EService/EService.Web/Controllers/DashboardController.cs
using System.Web.Mvc;
using EService.Data.Entity;
using EService.Web.Controllers.Base;

namespace EService.Web.Controllers
{
    public class DashboardController : BaseController
    {
        public ActionResult Index()
        {
            return View();
        }

        public PartialViewResult GetUserDashboard()
        {
            var userType = UserProfile.UserType;
            switch (userType)
            {
                case UserTypeEnum.SystemAdmin:
                    return PartialView("_SystemAdminDashbord");
                    break;
                case UserTypeEnum.FinanceUser:
                    return PartialView("_FinanceDashboard");
                    break;
                case UserTypeEnum.DepartmentUser:
                    return PartialView("_DepartmentDashboard");
                    break;
                case UserTypeEnum.ExternalUser:
                    return PartialView("_EServiceDashboard");
                    break;
                default:
                    return PartialView("_EmptyDashboard");
                    break;
            }
        }

        
    }
}

EService/EService.Web/Controllers/UserController.cs
using System;
using System.Linq;
using System.Text;
using System.Web.Mvc;
using EService.Core.Security;
using EService.Data.Entity;
using EService.Data.Entity.Entity;
using EService.Service.Logic;
using EService.Service.Model;
using EService.Web.Controllers.Base;
using EService.Web.Helper;
using EService.Web.Models;

namespace EService.Web.Controllers
{
    /// <summary>
    /// Controller for system admin to create department users and so on
    /// </summary>
    public class UserController : SystemAdminBaseController
    {
        private ServiceContext context;
        private UserService userService;
        private UserTypeService userTypeService;
        private DepartmentService departmentService;

        public UserController()
        {
            context = new ServiceContext();
            userService = new UserService(context);
            userTypeService = new UserTypeService(context);
            departmentService = new DepartmentService(context);
        }

        public ActionResult Index()
        {
            return View();
        }

        public JsonResult Initialize()
        {
            var result = new ResponseObject();
            try
            {
                var users = userService.GetUsers().ToList();
                var userTypes = userTypeService.FindAllAsNoTracking(o => !o.IsDeleted).AsEnumerable().Select(o => new LookupItem() { Active = true, Id = o.UserTypeId, Description = o.UserTypeName }).ToList();
                var departments = departmentService.FindAllAsNoTracking(o => !o.IsDeleted).AsEnumerable().Select(o => new LookupItem() { Active = true, Id = o.DepartmentId, Description = o.DepartmentName }).ToList();

                var newDepartmentUser = new DepartmentUserCreateViewModel();

                result.Data = new UserViewModel() { UserList = users, UserTypes = userTypes, Departments = departments, NewDepartmentUserModel = newDepartmentUser };
                result.IsSuccess = true;
            }
            catch (Exception)
            {
                result.IsSuccess = false;
                result.Message = "Error while obtaining users list.";
            }
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult SaveDepartmentUser(DepartmentUserCreateViewModel model)
        {
            var result = new ResponseObject();
            try
            {
                if (ModelState.IsValid)
                {
                    var user = new User()
                    {
                        DepartmentId = model.DepartmentId,
                        UserName = model.UserName,
                        Email = model.Email,
                        FirstName = model.FirstName,
                        LastName = model.LastName,
                        UserTypeId = model.UserTypeId ?? (int)UserTypeEnum.DepartmentUser,
                        Password = model.Password.ToMd5()
                    };
                    var saveResult = userService.SaveDepartmentUser(user);
                    if (saveResult.IsSuccess)
                    {
                        return Initialize();
                    }
                    else
                    {
                        result.IsSuccess = false;
                        result.Message = saveResult.Message;
                    }
                }
                else
                {
                    result.Message = ModelState.GetModelStateError();
                    result.IsSuccess = true;
                }
            }
            catch (Exception ex)
            {
                result.Message = "Error while saving department  user.";
                result.IsSuccess = false;
                LogError(ex);
            }
            return Json(result);
        }

        //public ActionResult ChangePassword()
        //{
        //    var model = new ChangePasswordViewModel();
        //    try
        //    {
        //        model.UserName = UserProfile.UserName;
        //        return View(model);
        //    }
        //    catch (Exception ex)
        //    {

        //    }
        //    return ErrorResult();
        //    //UserProfile.UserName
        //}

        //[HttpPost]
        //public JsonResult ChangePassword(ChangePasswordViewModel model)
        //{
        //    var result = new JsonResponseObject();
        //    try
        //    {
        //        if (ModelState.IsValid)
        //        {
        //            ResponseObject saveResult = userService.ChangePassword(UserProfile.UserId, model.CurrentPassword,
        //                model.NewPassword);
        //            result.IsSuccess = saveResult.IsSuccess;
        //            result.Message = saveResult.Message;
        //        }
        //        else
        //        {
        //            result.IsSuccess = false;
        //            result.Message = ModelState.GetModelStateError();
        //        }
        //    }
        //    catch (Exception ex)
        //    {
        //        result.IsSuccess = false;
        //        result.Message = "Error while changing password.";

        //    }
        //    return Json(result);
        //}

    }
}

EService/EService.Web/Views/Dashboard/Index.cshtml
@{
    ViewBag.Title = "Dashboard";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section Scripts{
    <script type="text/javascript">
        $(function () {

        });
    </script>
}

<div class="row">
    @{
        Html.RenderAction("GetUserDashboard");

    }
</div>

EService/EService.Web/Views/Dashboard/_DepartmentDashboard.cshtml
@section Scripts{
    <script type="text/javascript">
        var DepartmentDashBoard = {}
        $(function () {
            initialize();
        });
        function initialize() {

        }
    </script>
}
<div class="col-lg-6">
    <div class="list-group">
        <a href="@Url.Action("Index", "UserServiceRequest", new { Area = "Department" })" class="list-group-item">
            Pending Service Requests for this department
        </a>
    </div>
</div>

EService/EService.Web/Views/Dashboard/_EServiceDashboard.cshtml
@using EService.Service.Logic.Enum
@using EService.Web.App_LocalResources
@section Scripts{
    <script type="text/javascript">
        $(function () {

        });
    </script>
}
<div class="req-filter-header">
    <div class="row">
        <div class="col-sm-6">
            <h3>E-Services</h3>
        </div>
        <div class="col-sm-6">
            <div class="req-hist">
                <form action="" method="post">
                    <label>Request History</label>
                    <div class="form-group">
                        <input type="text" name="search" class="form-control" placeholder="Search">
                        <button type="submit" name="submit"><i class="fa fa-search"></i></button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<div class="e-servicer-wrapper">
    <div class="row">
        <div class="col-md-4 col-sm-6">
            <div class="e-service-block">
                <a href="@Url.Action("Description", "ServiceRequest", new { Area = "", serviceId = (int?)ServiceEnum.CranePermitRequest })">
                    <figure class="e-service-thumbnail">
                        <span><img src="@Url.Content("~/images/icon-crane.png")" alt="icon-crane.png"></span>
                    </figure>
                    <h6>Crane Permit <i class="fa fa-chevron-right"></i></h6>
                </a>
            </div>
        </div>
        <div class="col-md-4 col-sm-6">
            <div class="e-service-block">
                <a href="@Url.Action("Description", "ServiceRequest", new { Area = "" , serviceId = (int?)ServiceEnum.BuildingHeightRequest})">
                    <figure class="e-service-thumbnail">
                        <span><img src="@Url.Content("~/images/icon-building.png")" alt="icon-building.png"></span>
                    </figure>
                    <h6>Building Height <i class="fa fa-chevron-right"></i></h6>
                </a>
            </div>
        </div>
        <div class="col-md-4 col-sm-6">
            <div class="e-service-block">
                <a href="@Url.Action("Description", "ServiceRequest", new { Area = "", serviceId = (int?)ServiceEnum.AircraftWarningLight })">
                    <figure class="e-service-thumbnail">
                        <span><img src="@Url.Content("~/images/icon-airplane.png")" alt="icon-airplane.png"></span>
                    </figure>
                    <h6>Aircraft Warning light <i class="fa fa-chevron-right"></i></h6>
                </a>
            </div>
        </div>
        <div class="col-md-4 col-sm-6">
            <div class="e-service-block">
                <a href="@Url.Action("Description", "ServiceRequest", new { Area = "" , serviceId = (int?)ServiceEnum.GroundHandlingRequest})">
                    <figure class="e-service-thumbnail">
                        <span><img src="@Url.Content("~/images/icon-airplane-landing.png")" alt="icon-airplane-landing.png"></span>
                    </figure>
                    <h6>Ground Handling<i class="fa fa-chevron-right"></i></h6>
                </a>
            </div>
        </div>
        
        <div class="col-md-4 col-sm-6">
            <div class="e-service-block">
                <a href="@Url.Action("Description", "ServiceRequest", new { Area = "" , serviceId = (int?)ServiceEnum.AircraftDismantlingRequest})">
                    <figure class="e-service-thumbnail">
                        <span><img src="@Url.Content("~/images/icon-dismantling.png")" alt="icon-dismantling.png"></span>
                    </figure>
                    <h6>Aircraft dismantling <i class="fa fa-chevron-right"></i></h6>
                </a>
            </div>
        </div>

        <div class="col-md-4 col-sm-6">
            <div class="e-service-block">
                <a href="@Url.Action("Description", "ServiceRequest", new { Area = "", serviceId = (int?)ServiceEnum.ExitOfAircraftSparePartsRequest })">
                    <figure class="e-service-thumbnail">
                        <span><img src="@Url.Content("~/images/icon-spare-parts.png")" alt="icon-spare-parts.png"></span>
                    </figure>
                    <h6>Exit of spare parts <i class="fa fa-chevron-right"></i></h6>
                </a>
            </div>
        </div>
        <div class="col-md-4 col-sm-6">
            <div class="e-service-block">
                <a href="@Url.Action("Description", "ServiceRequest", new { Area = "", serviceId = (int?)ServiceEnum.AircraftMaintenanceRequest })">
                    <figure class="e-service-thumbnail">
                        <span><img src="@Url.Content("~/images/icon-maintenance.png")" alt="icon-maintenance.png"></span>
                    </figure>
                    <h6>Aircraft maintenance <i class="fa fa-chevron-right"></i></h6>
                </a>
            </div>
        </div>
        <div class="col-md-4 col-sm-6">
            <div class="e-service-block">
                <a href="@Url.Action("Description", "ServiceRequest", new { Area = "", serviceId = (int?)ServiceEnum.TradeLicenseRequest })">
                    <figure class="e-service-thumbnail">
                        <span><img src="@Url.Content("~/images/icon-trade.png")" alt="icon-trade.png"></span>
                    </figure>
                    <h6>Trade license <i class="fa fa-chevron-right"></i></h6>
                </a>
            </div>
        </div>
        <div class="col-md-4 col-sm-6">
            <div class="e-service-block">
                <a href="@Url.Action("Description", "ServiceRequest", new { Area = "", serviceId = (int?)ServiceEnum.MeteorologicalDataRequest })">
                <figure class="e-service-thumbnail">
                <span><img src="@Url.Content("~/images/icon-data.png")" alt="icon-data.png"></span>
                </figure>
                <h6>Meteorological data <i class="fa fa-chevron-right"></i></h6>
                </a>
            </div>
        </div>
    </div>
</div>

EService/EService.Web/Views/Dashboard/_FinanceDashboard.cshtml
@section Scripts{
    <script type="text/javascript">
        var DepartmentDashBoard = {}
        $(function () {
            initialize();
        });
        function initialize() {

        }
    </script>
}
<span class="alert alert-info">Deprtment User</span>
<div class="col-lg-6">
    <div class="list-group">
        <a href="@Url.Action("Index", "UserServiceRequest", new { Area = "Department" })" class="list-group-item">
            Pending Service Requests for this department
        </a>
        <a href="@Url.Action("Index", "UserServiceRequest", new { Area = "Finance" })" class="list-group-item">
            Approve Payment
        </a>
       

    </div>
</div>

EService/EService.Web/Views/Dashboard/_SystemAdminDashbord.cshtml
@section Scripts{
    <script type="text/javascript">
        $(function () {

        });
    </script>
}
<div class="col-md-6 col-sm-12">
    <span class="alert-info alert">
        <b>Welcome</b>! You are logged in as system admin.
    </span>
    
</div>

<div class="col-md-6 col-sm-12">
    <div class="list-group">
        <a href="@Url.Action("Index", "UserServiceRequest", new { Area = "Admin" })" class="list-group-item">
            Manage Service Requests
        </a>
        <a href="@Url.Action("Index", "User", new { Area = "" })" class="list-group-item">
            Manage User
        </a>
        <a href="@Url.Action("Index", "ResetPassword", new { Area = "" })" class="list-group-item">
            Reset Password
        </a>
        <a href="@Url.Action("Index", "ServiceApprovalFlowConfiguration", new { Area = "" })" class="list-group-item">
            Manage Service Approval Flow
        </a>
        <a href="@Url.Action("Index", "SMTP", new { Area = "Configure" })" class="list-group-item">
            SMTP Configuration
        </a>
        <a href="@Url.Action("Index", "Service", new {Area = "Configure"})" class="list-group-item">
            Service Information Configuration
        </a>
        <a href="@Url.Action("Index", "ServiceRequestSummary", new {Area = "Report"})" class="list-group-item">
            Service Request Summary Report
        </a>
        <a href="@Url.Action("Index", "ApplicableFees", new { Area = "Admin" })" class="list-group-item">
            Applicable Fees Lookup
        </a>
        <a href="@Url.Action("Index", "PaymentKeyConfiguration", new { Area = "Admin" })" class="list-group-item">
            Payment key Configuration
        </a>
    </div>
</div>