EService/EService.Web/Models/MeteorologicalDataRequestViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using EService.Web.App_LocalResources;

namespace EService.Web.Models
{
    public class MeteorologicalDataRequestViewModel : EServiceCreateBaseViewModel, IValidatableObject
    {
        public DateTime ApplicationDate { get; set; }
        public int UserServiceRequestMasterId { get; set; }

        #region "Contact Information"

        [Required(ErrorMessageResourceType = typeof(MeteorologicalDataRequestResource), ErrorMessageResourceName = "EmailRequired")]
        public string Email { get; set; }
        public string Department { get; set; }
        [Required(ErrorMessageResourceType = typeof(MeteorologicalDataRequestResource), ErrorMessageResourceName = "PhoneNoRequired")]
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string Address { get; set; }

        #endregion

        public bool DataRangeDaily { get; set; }
        public bool DataRangeHourly { get; set; }
        public bool DataRangeMonthly { get; set; }
        public bool DataRangeYearly { get; set; }
        public bool DataRangeSelectPeriod { get; set; }
        public DateTime? CustomRangeStartDate { get; set; }
        public DateTime? CustomRangeEndDate { get; set; }

        public List<MetWeatherTypeReportViewModel> WeatherTypes { get; set; }
        public List<MetWeatherElementReportViewModel> WeatherElements { get; set; }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        {
            var result = new List<ValidationResult>();
            if ((CustomRangeEndDate == null || CustomRangeStartDate == null))
            {
                result.Add(new ValidationResult("Custom Date Range has to be entered."));
            }
            else if (CustomRangeEndDate < CustomRangeStartDate)
            {
                result.Add(new ValidationResult("Custom Range End Date must be greater than Start Date."));
            }

            return result;
            throw new NotImplementedException();
        }
    }

    public class MetWeatherTypeReportViewModel
    {
        public int WeatherTypeReportId { get; set; }
        public string WeatherTypeDescription { get; set; }
        public bool IsActive { get; set; }
    }

    public class MetWeatherElementReportViewModel
    {
        public int WeatherElementId { get; set; }
        public bool IsActive { get; set; }
        public string OtherName { get; set; }

        public string WeatherElementDescription { get; set; }
        public bool IsOther { get; set; }
    }
}

EService/EService.Web/Models/UserServiceRequestViewModel.cs
using System;

namespace EService.Web.Models
{
    public class UserServiceRequestViewModel
    {
        public int UserServiceRequestMasterId { get; set; }
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string Email { get; set; }
        public DateTime RequestDateTime { get; set; }
        public int ServiceId { get; set; }
        public string ServiceName { get; set; }
        public int Status { get; set; }

        #region "Reject"
        public string Comments { get; set; }
        public bool IsUserSelectedForReject { get; set; }
        public int? SelectedStageId { get; set; }
        #endregion
    }
}

EService/EService.Web/Areas/Admin/Controllers/UserServiceRequestController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EService.Core;
using EService.Service.Logic;
using EService.Service.Logic.Enum;
using EService.Service.Model;
using EService.Web.Controllers.Base;
using EService.Web.Helper;
using EService.Web.Models;
using EService.Web.Models.ServiceRequestOperation;

namespace EService.Web.Areas.Admin.Controllers
{
    public class UserServiceRequestController : SystemAdminBaseController
    {
        private ServiceInfoService serviceInfoService;
        private UserServiceRequestMasterService userRequestService;
        private ServiceContext context;

        public UserServiceRequestController()
        {
            context = new ServiceContext();
            userRequestService = new UserServiceRequestMasterService(context);
            serviceInfoService = new ServiceInfoService(context);
        }

        public ActionResult Index()
        {
            return View();
        }

        public JsonResult Initialize()
        {
            var result = new ResponseObject();
            try
            {
                var model = new UserServiceRequestOperationViewModel
                {
                    Services = serviceInfoService.FindAllAsNoTracking(o => o.IsActive && !o.IsDeleted)
                        .Select(o => new SelectListModel()
                        {
                            Description = o.ServiceName,
                            Id = o.ServiceId
                        }).ToList(),
                    Statuses = (ServiceFlowStateEnum.Active).ToDictionary().Select(o => new SelectListModel()
                    {
                        Description = o.Value,
                        Id = o.Key
                    }).ToList()
                };
                result.IsSuccess = true;
                result.Data = new
                {
                    SearchModel = model,
                    Records = new List<UserServiceRequestModel>()
                };
            }
            catch (Exception ex)
            {
                LogError(ex);
                result.IsSuccess = false;
                result.Message = "Error while obtaining information for service.";
            }
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult Search(UserServiceRequestOperationViewModel searchModel)
        {
            var result = new ResponseObject();
            try
            {
                var data = userRequestService.GetServiceRequests(null, searchModel.ServiceId, searchModel.DateFrom, searchModel.DateTo, searchModel.ServiceStatus, searchModel.ApplicantEmail, true).ToList();
                result.Data = data;
                result.IsSuccess = true;
            }
            catch (Exception ex)
            {
                LogError(ex);
                result.IsSuccess = false;
                result.Message = "Error while obtaining information for service.";
            }
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        public JsonResult InitializeDetail()
        {
            var result = new JsonResponseObject();
            try
            {
                var serviceId = TempData.Peek("ServiceRequestDetailViewKey").ToNInt32();
                if (serviceId == null)
                {
                    result.IsSuccess = false;
                    result.Message = "Invalid Service Request information provided";
                }
                else
                {
                    var id = serviceId.Value;
                    var data = userRequestService.Find(o => !o.IsDeleted && o.UserServiceRequestMasterId == id);
                    if (data == null)
                    {
                        result.IsSuccess = false;
                        result.Message = "Invalid Service Request information provided";
                    }
                    else
                    {
                        var html = "";
                        object objectData = null;
                        switch (data.ServiceId)
                        {
                            case (int)ServiceEnum.CranePermitRequest:
                                var serviceData = userRequestService.GetCranePermitRequest(id, true);
                                objectData = serviceData;
                                html = RenderPartialView("_CranePermitRequestDetail", serviceData);
                                break;
                            case (int)ServiceEnum.AircraftMaintenanceRequest:
                                var amData = userRequestService.GetAircraftMaintenanceRequest(id, true);
                                objectData = amData;
                                html = RenderPartialView("_AircraftMaintenanceRequestDetail", amData);
                                break;
                            case (int)ServiceEnum.AircraftDismantlingRequest:
                                var adData = userRequestService.GetAircraftDismantlingRequest(id, true);
                                objectData = adData;
                                html = RenderPartialView("_AircraftDsimantlingRequestDetail", adData);
                                break;
                            case (int)ServiceEnum.AircraftWarningLight:
                                var awData = userRequestService.GetAircraftWarningRequest(id);
                                objectData = awData;
                                html = RenderPartialView("_AircraftWarningLightDetail", awData);
                                break;
                            case (int)ServiceEnum.TradeLicenseRequest:
                                var tlData = userRequestService.GetTradeLicenseRequest(id, true);
                                objectData = tlData;
                                html = RenderPartialView("_TradeLicenseRequestDetail", tlData);
                                break;
                            case (int)ServiceEnum.MeteorologicalDataRequest:
                                var mrData = userRequestService.GetMeteorologicalDataRequest(id);
                                objectData = mrData;
                                html = RenderPartialView("_MeteorologicalDataRequest", mrData);
                                break;
                            case (int)ServiceEnum.ExitOfAircraftSparePartsRequest:
                                var eoSData = userRequestService.GetExitOfSparePartsRequest(id);
                                objectData = eoSData;
                                html = RenderPartialView("_ExitOfAircraftSpareParts", eoSData);
                                break;
                            case (int)ServiceEnum.BuildingHeightRequest:
                                var bHRData = userRequestService.GetBuildingHeightRequest(id);
                                objectData = bHRData;
                                html = RenderPartialView("_BuildingHeightRequestDetail", bHRData);
                                break;
                            case (int)ServiceEnum.GroundHandlingRequest:
                                var ghData = userRequestService.GetGroundHandlingRequset(id);
                                objectData = ghData;
                                html = RenderPartialView("_GroundHandlingDetail", ghData);
                                break;
                            default:
                                html = "Service Not Implemented Yet";
                                break;
                        }
                        result.IsSuccess = true;
                        var history = userRequestService.GetRequestFlowStageDepartmentHistories(id).ToList();
                        result.Data = new { Html = html, Data = objectData, History = history };
                    }
                }

            }
            catch (Exception ex)
            {
                LogError(ex);
                result.IsSuccess = false;
                result.Message = "Error while loading detail data.";
            }
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Detail(int id)
        {
            try
            {
                var data = userRequestService.Find(o => !o.IsDeleted && o.UserServiceRequestMasterId == id);
                if (data == null)
                {
                    return ErrorResult("Invalid Service Request information selected. Please make sure you selected proper request.");
                }
                TempData["ServiceRequestDetailViewKey"] = id;
                return View();
            }
            catch (Exception ex)
            {
                LogError(ex);

            }
            return ErrorResult("Error while obtaining record");
        }

        [HttpPost]
        public JsonResult Approve(int id)
        {
            var result = new JsonResponseObject();
            try
            {
                var approveResult = userRequestService.Approve(id, 0, UserProfile.UserId, true);
                result.IsSuccess = approveResult.Item1;
                result.Message = approveResult.Item2;
                if (approveResult.Item1)
                {
                    //
                    TriggerEmail(FIAEmailType.Approved, approveResult.Item3.ServiceRequestFlowStageDepartmentId);
                }
            }
            catch (Exception ex)
            {
                LogError(ex);
                result.IsSuccess = false;
                result.Message = "Error while approving selected request.";
            }

            return Json(result);
        }
    }
}

EService/EService.Web/Controllers/UserServiceRequestController.cs
using System;
using System.Web.Mvc;
using EService.Service.Logic;
using EService.Web.Controllers.Base;
using EService.Web.Models;

namespace EService.Web.Controllers
{
    public class UserServiceRequestMasterController : BaseController
    {
        private UserServiceRequestMasterService userServiceRequestMasterService;
        private UserAttachmentService userAttachmentService;

        public UserServiceRequestMasterController()
        {
            userServiceRequestMasterService = new UserServiceRequestMasterService(serviceContext);
            userAttachmentService = new UserAttachmentService(serviceContext);
        }

        public ActionResult Index()
        {
            return View();
        }

        public JsonResult UploadedFiles(int userServiceRequestmasterId)
        {
            var result = new JsonResponseObject();

            try
            {
                result.Data = userAttachmentService.GetUploadedFileInfoServiceModels(userServiceRequestmasterId);
                result.IsSuccess = true;
            }
            catch (Exception ex)
            {
                LogError(ex);
                result.IsSuccess = false;
                result.Message = "Error while ";
            }
            return Json(result, JsonRequestBehavior.AllowGet);
        }

    }
}

EService/EService.Web/Areas/Department/Views/UserServiceRequest/Edit.cshtml
@using EService.Web.App_GlobalResources
@using EService.Web.App_LocalResources
@model EService.Web.Models.CranePermitRequestViewModel
@{
    ViewBag.Title = "Edit Service Request";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<span class="alert alert-info">Edit Page not implement for selected request.</span>

EService/EService.Web/Areas/Department/Views/UserServiceRequest/EditCranePermitRequest.cshtml
@using EService.Web.App_GlobalResources
@using EService.Web.App_LocalResources
@model EService.Service.Model.CranePermitRequestServiceModel

@section scripts{
    <script type="text/javascript">
        var CranePermitRequestVM = {
            AddNewModel: {},
            SaveRequest: function () {
                if (!$('#frm').valid()) {
                    return false;
                }
                var model = ko.toJS(CranePermitRequestVM.AddNewModel);
                model.OperationDate = moment(model.OperationDate).isValid() ? moment(model.OperationDate).format('DD/MM/YY') : null;
                model.ApplicationDate = moment(model.ApplicationDate).isValid() ? moment(model.ApplicationDate).format('DD/MM/YY') : null;
                ajaxRequest('@Url.Action("UpdateCranePermitRequest")', 'POST', { data: { model: model } }, function (resp) {
                    if (resp.IsSuccess) {
                        showMessage('Crane Permit Request', resp.Message, 'success', function () {
                            //
                            window.location = '@Url.Action("Detail","UserServiceRequest", new {Area="Department"})';
                        });
                    } else {
                        showMessage('Crane Permit Request', resp.Message, 'error');
                    }
                });
            }
        };

        $(function () {
            initialize();
        });

        function initialize() {
            ajaxRequest('@Url.Action("InitializeEdit")', 'GET', {}, function (resp) {
                if (resp.IsSuccess) {
                    if (!ko.dataFor($('#frm')[0])) {
                        CranePermitRequestVM.AddNewModel = ko.mapping.fromJS(resp.Data);

                        ko.applyBindings(CranePermitRequestVM, $('#frm')[0]);
                    } else {
                        ko.mapping.fromJS(resp.Data, {}, CranePermitRequestVM);
                    }
                } else {
                    console.log(resp.Message);
                }
            });
        }
    </script>
}
<form id="frm" class="form-horizontal">
    <div data-bind="with:AddNewModel">

        <div class="form-group">
            <div class="col-sm-4 control-label">
                @Html.LabelFor(model => model.ApplicationDate, CranePermitLocationResource.ApplicationDate)
                <span class="red">*</span>
            </div>
            <div class="col-sm-8">
                @Html.TextBoxFor(model => model.ApplicationDate, new { @class = "form-control", data_bind = "datePicker:ApplicationDate" })
                @Html.ValidationMessageFor(model => model.ApplicationDate)
            </div>
        </div>

        <div class="form-group">
            <div class="col-sm-4 control-label">
                @Html.LabelFor(model => model.ApplicantName, CranePermitLocationResource.ApplicantName)
                <span class="red">*</span>
            </div>
            <div class="col-sm-8">
                @Html.TextBoxFor(model => model.ApplicantName, new { @class = "form-control", data_bind = "value:ApplicantName" })
                @Html.ValidationMessageFor(model => model.ApplicantName)
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-4 control-label">
                @Html.LabelFor(model => model.CompanyName, CranePermitLocationResource.CompanyName)
                <span class="red">*</span>
            </div>
            <div class="col-sm-8">
                @Html.TextBoxFor(model => model.CompanyName, new { @class = "form-control", data_bind = "value:CompanyName" })
                @Html.ValidationMessageFor(model => model.CompanyName)
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-4 control-label">
                @Html.LabelFor(model => model.Position, CranePermitLocationResource.Position)
            </div>
            <div class="col-sm-8">
                @Html.TextBoxFor(model => model.Position, new { @class = "form-control", data_bind = "value:Position" })
                @Html.ValidationMessageFor(model => model.Position)
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-4 control-label">
                @Html.LabelFor(model => model.ContactNumber, CranePermitLocationResource.ContactNumber)
                <span class="red">*</span>
            </div>
            <div class="col-sm-8">
                @Html.TextBoxFor(model => model.ContactNumber, new { @class = "form-control", data_bind = "value:ContactNumber" })
                @Html.ValidationMessageFor(model => model.ContactNumber)
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-4 control-label">
                @Html.LabelFor(model => model.ApplicantEmail, CranePermitLocationResource.ApplicantEmail)
                <span class="red">*</span>
            </div>
            <span class="red">*</span>
            <div class="col-sm-8">
                @Html.TextBoxFor(model => model.ApplicantEmail, new { @class = "form-control", data_bind = "value:ApplicantEmail" })
                @Html.ValidationMessageFor(model => model.ApplicantEmail)
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.IsNewApplication, CranePermitLocationResource.IsNewApplication, new { @class = "col-sm-4 control-label" })
            <div class="col-sm-8">
                @Html.CheckBoxFor(model => model.IsNewApplication, new { @class = "form-control", data_bind = "value:IsNewApplication" })
                @Html.ValidationMessageFor(model => model.IsNewApplication)
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.PreviousPermitNumbers, CranePermitLocationResource.PreviousPermitNumbers, new { @class = "col-sm-4 control-label" })
            <div class="col-sm-8">
                @Html.TextBoxFor(model => model.PreviousPermitNumbers, new { @class = "form-control", data_bind = "value:PreviousPermitNumbers" })
                @Html.ValidationMessageFor(model => model.PreviousPermitNumbers)
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.CraneLocation, CranePermitLocationResource.LocationOfCrane, new { @class = "col-sm-4 control-label" })
            <div class="col-sm-8">
                @Html.TextBoxFor(model => model.CraneLocation, new { @class = "form-control", data_bind = "value:LocationOfCrane" })
                @Html.ValidationMessageFor(model => model.CraneLocation)
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.NorthingsEastings, CranePermitLocationResource.NorthingsEastings, new { @class = "col-sm-4 control-label" })
            <div class="col-sm-8">
                @Html.TextBoxFor(model => model.NorthingsEastings, new { @class = "form-control", data_bind = "value:NorthingsEastings" })
                @Html.ValidationMessageFor(model => model.NorthingsEastings)
            </div>
        </div>

        <div class="form-group">
            <div class="col-sm-4 control-label">
                @Html.LabelFor(model => model.OperationDate, CranePermitLocationResource.OperationDate)
                <span class="red">*</span>
            </div>
            <div class="col-sm-8">
                @Html.TextBoxFor(model => model.OperationDate, new { @class = "form-control", data_bind = "datePicker:OperationDate" })
                @Html.ValidationMessageFor(model => model.OperationDate)
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-4 control-label">
                @Html.LabelFor(model => model.OperationTiming, CranePermitLocationResource.OperationTiming)
                <span class="red">*</span>
            </div>
            <div class="col-sm-8">
                @Html.TextBoxFor(model => model.OperationTiming, new { @class = "form-control", data_bind = "value:OperationTiming" })
                @Html.ValidationMessageFor(model => model.OperationTiming)
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-4 control-label">
                @Html.LabelFor(model => model.MaxOperatingHeight, CranePermitLocationResource.MaxOperatingHeight)
                <span class="red">*</span>
            </div>
            <div class="col-sm-8">
                @Html.TextBoxFor(model => model.MaxOperatingHeight, new { @class = "form-control", data_bind = "value:MaxOperatingHeight" })
                @Html.ValidationMessageFor(model => model.MaxOperatingHeight)
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.PurposeOfUser, CranePermitLocationResource.PurposeOfUser, new { @class = "col-sm-4 control-label" })
            <div class="col-sm-8">
                @Html.TextBoxFor(model => model.PurposeOfUser, new { @class = "form-control", data_bind = "value:PurposeOfUser" })
                @Html.ValidationMessageFor(model => model.PurposeOfUser)
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-4 control-label">
                @Html.LabelFor(model => model.CraneOperatingCompany, CranePermitLocationResource.CraneOperatingCompany)
                <span class="red">*</span>
            </div>
            <div class="col-sm-8">
                @Html.TextBoxFor(model => model.CraneOperatingCompany, new { @class = "form-control", data_bind = "value:CraneOperatingCompany" })
                @Html.ValidationMessageFor(model => model.CraneOperatingCompany)
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-4 control-label">
                @Html.LabelFor(model => model.OperatorName, CranePermitLocationResource.OperatorName)
                <span class="red">*</span>
            </div>
            <div class="col-sm-8">
                @Html.TextBoxFor(model => model.OperatorName, new { @class = "form-control", data_bind = "value:OperatorName" })
                @Html.ValidationMessageFor(model => model.OperatorName)
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-4 control-label">
                @Html.LabelFor(model => model.OperatorContactNumber, CranePermitLocationResource.OperatorContactNumber)
                <span class="red">*</span>
            </div>
            <div class="col-sm-8">
                @Html.TextBoxFor(model => model.OperatorContactNumber, new { @class = "form-control", data_bind = "value:OperatorContactNumber" })
                @Html.ValidationMessageFor(model => model.OperatorContactNumber)
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-4 control-label">@CranePermitLocationResource.CraneType</label>
            <div class="col-sm-8" data-bind="foreach:CraneTypeSelectionViewModels">
                <div class="col-xs-4 col-md-2">
                    <label><input type="checkbox" data-bind="checked:IsSelected" /><span data-bind="text: CraneTypeName"></span></label>
                </div>
                <div data-bind="if: IsOther()===true && IsSelected() === true ">
                    <input type="text" data-bind="value:OtherCraneTypeName" class="form-control col-xs-4" />
                </div>
            </div>
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-8">
            <input type="button" id="btnSave" class="btn btn-primary" data-bind="click: SaveRequest" value="@GlobalResource.Submit" />
        </div>
    </div>

</form>

EService/EService.Web/Areas/Department/Views/UserServiceRequest/Index.cshtml
@model List<EService.Service.Model.UserServiceRequestFlowStageModel>

@{
    ViewBag.Title = "User Service Requests";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>User Service Requests</h2>

@section scripts{
    <script type="text/javascript">
        var ServiceRequestVM = {
            Records: {},
            Initialie: function () {
                ajaxRequest('@Url.Action("Initialize")', 'GET', {}, function (resp) {
                    if (resp.IsSuccess) {
                        if (!ko.dataFor($('#mainContent')[0])) {
                            ServiceRequestVM.Records = ko.mapping.fromJS(resp.Data);
                            ServiceRequestVM.viewDetailClick = function (item) {
                                window.location = '/Department/UserServiceRequest/Detail/' + item.UserServiceRequestMasterId();
                            }
                            ko.applyBindings(ServiceRequestVM, $('#mainContent')[0]);
                        } else {
                            ko.mapping.fromJS(resp.Data, {}, ServiceRequestVM.Records);
                        }
                    } else {
                        showMessage('User Service Request Master', resp.Message, 'error');
                    }
                });
            }
        }
        $(function () {
            ServiceRequestVM.Initialie();
        });
    </script>
}
<div id="mainContent">
    <table class="table table-bordered table-condensed table-striped">
        <thead>
            <tr>
                <th>Service Name</th>
                <th>NOC Req Ref No </th>
                <th>User (Email)</th>
                <th>Requested Date Time</th>
                <th>Request Status</th>
                <th>Department Status</th>
                <th></th>
            </tr>
        </thead>
        <tbody data-bind="foreach: Records">
            <tr>
                <td data-bind="text: ServiceName"></td>
                <td data-bind="text: RegistrationNo"></td>
                <td data-bind="text: UserName()+'( '+Email()+' )' "></td>
                <td data-bind="text: moment(RequestDateTime()).format('DD/MM/YY hh:mm:ss a')"></td>
                <td data-bind="text: ServiceRequestStatusName"></td>
                <td data-bind="text: DepartmentServiceRequestStatusName"></td>
                <td><a href="javscript:void()" class="btn btn-xs btn-info" data-bind="click:$root.viewDetailClick">&nbsp; View Detail</a></td>
            </tr>
        </tbody>
    </table>
</div>