EService/EService.Web/Controllers/ServiceRequestController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EService.Core;
using EService.Data.Entity.Entity;
using EService.Service.Logic;
using EService.Service.Logic.Enum;
using EService.Service.Model;
using EService.Web.Controllers.Base;
using EService.Web.Helper;
using EService.Web.Models;
using EService.Web.Models.ServiceRequestOperation;
using Nelibur.ObjectMapper;

namespace EService.Web.Controllers
{
    /// <summary>
    /// controller for requesting service
    /// </summary>
    public class ServiceRequestController : ExternalUserBaseController
    {
        private ServiceInfoService serviceInfoService;
        private UserServiceRequestMasterService userRequestService;
        private ServiceContext context;
        private GroundHandlingRequestService groundHandlingRequestService;

        public ServiceRequestController()
        {
            context = new ServiceContext();
            userRequestService = new UserServiceRequestMasterService(context);
            serviceInfoService = new ServiceInfoService(context);
            groundHandlingRequestService = new GroundHandlingRequestService(context);
        }

        public ActionResult Index(int serviceId)
        {
            try
            {
                var service = serviceInfoService.Find(o => o.ServiceId == serviceId && o.IsActive && !o.IsDeleted);
                if (service != null)
                {
                    TempData["ServiceRequestViewKey"] = serviceId;
                    return View();
                }
                else
                {
                    return ErrorResult("Invalid Service info selected.");
                }
            }
            catch (Exception ex)
            {
                LogError(ex);
                return ErrorResult("Error while selecting service information.");
            }
        }

        public JsonResult Initialize()
        {
            var result = new ResponseObject();
            try
            {
                var serviceId = TempData.Peek("ServiceRequestViewKey").ToNInt32();
                if (serviceId == null)
                {
                    result.IsSuccess = false;
                    result.Message = "Invalid Operation. Please try again by navigating from dashboard.";
                }
                else
                {
                    var serviceInfo = serviceInfoService.Find(o => o.IsActive && !o.IsDeleted && o.ServiceId == serviceId);
                    var data = userRequestService.GetServiceRequests(UserProfile.UserId, serviceId).ToList();
                    result.Data = new
                    {
                        Records = data,
                        ServiceName = serviceInfo.ServiceName,
                        SearchModel = new ServiceRequestSearchViewModel()
                        {
                            ServiceId = serviceId,
                            ServiceStatusList = ServiceFlowStateEnum.Active.ToDictionary().Select(o => new SelectListModel() { Id = o.Key, Description = o.Value }).ToList()
                        }
                    };
                    result.IsSuccess = true;
                }
            }
            catch (Exception ex)
            {
                result.IsSuccess = false;
                LogError(ex);
                result.Message = "Error while obtaining information for service.";
            }
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult Search(ServiceRequestSearchViewModel searchModel)
        {
            var result = new ResponseObject();
            try
            {
                if (searchModel.ServiceId == null)
                {
                    result.IsSuccess = false;
                    result.Message = "Invalid Service information selected. Please try again by navigating to dashboard.";
                }
                else
                {
                    //var serviceInfo = serviceInfoService.Find(o => o.IsActive && !o.IsDeleted && o.ServiceId == searchModel.ServiceId);
                    var data = userRequestService.GetServiceRequests(UserProfile.UserId, searchModel.ServiceId.Value, searchModel.DateFrom, searchModel.DateTo, searchModel.ServiceStatus, "", false, searchModel.Skip, searchModel.PageSize).ToList();
                    result.Data = data;
                    result.IsSuccess = true;
                }

            }
            catch (Exception ex)
            {
                LogError(ex);
                result.IsSuccess = false;
                result.Message = "Error while obtaining information for service.";
            }
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Create()
        {
            var serviceId = TempData["ServiceRequestViewKey"].ToNInt32();
            if (serviceId == null)
            {
                return ErrorResult("Invalid Operation. Please try again.");
            }
            var service = (ServiceEnum)serviceId.Value;
            switch (service)
            {
                case ServiceEnum.AircraftDismantlingRequest:
                    return RedirectToAction("Create", "AircraftDismantlingRequest");
                case ServiceEnum.AircraftMaintenanceRequest:
                    return RedirectToAction("Create", "AircraftMaintenanceRequest");
                case ServiceEnum.AircraftWarningLight:
                    return RedirectToAction("Create", "AircraftWarningLight");
                case ServiceEnum.BuildingHeightRequest:
                    return RedirectToAction("Create", "BuildingHeightRequest");
                case ServiceEnum.CranePermitRequest:
                    return RedirectToAction("Create", "CranePermitRequest");
                case ServiceEnum.ExitOfAircraftSparePartsRequest:
                    return RedirectToAction("Create", "ExitSparePartsRequest");
                case ServiceEnum.MeteorologicalDataRequest:
                    return RedirectToAction("Create", "MeteorologicalData");
                case ServiceEnum.TradeLicenseRequest:
                    return RedirectToAction("Create", "TradeLicenseRequest");
                case ServiceEnum.GroundHandlingRequest:
                    return RedirectToAction("Create", "GroundHandlingRequest");
                default:
                    return ErrorResult("Matching Service Information not found");
            }

        }

        public JsonResult InitializeDetail()
        {
            var result = new JsonResponseObject();
            try
            {
                var serviceId = TempData.Peek(Constants.ServiceRequestDetailTempDataKey).ToNInt32();
                if (serviceId == null)
                {
                    result.IsSuccess = false;
                    result.Message = "Invalid Service Request information provided";
                }
                else
                {
                    var id = serviceId.Value;
                    var data = userRequestService.Find(o => !o.IsDeleted && o.UserServiceRequestMasterId == id && o.UserId == UserProfile.UserId);
                    if (data == null)
                    {
                        result.IsSuccess = false;
                        result.Message = "Invalid Service Request information provided";
                    }
                    else
                    {
                        var html = "";
                        object objectData = null;
                        switch (data.ServiceId)
                        {
                            case (int)ServiceEnum.CranePermitRequest:
                                var serviceData = userRequestService.GetCranePermitRequest(id, true);
                                objectData = serviceData;
                                html = RenderPartialView("_CranePermitRequestDetail", serviceData);
                                break;
                            case (int)ServiceEnum.AircraftMaintenanceRequest:
                                var amData = userRequestService.GetAircraftMaintenanceRequest(id, true);
                                objectData = amData;
                                html = RenderPartialView("_AircraftMaintenanceRequestDetail", amData);
                                break;
                            case (int)ServiceEnum.AircraftDismantlingRequest:
                                var adData = userRequestService.GetAircraftDismantlingRequest(id, true);
                                objectData = adData;
                                html = RenderPartialView("_AircraftDsimantlingRequestDetail", adData);
                                break;
                            case (int)ServiceEnum.AircraftWarningLight:
                                var awData = userRequestService.GetAircraftWarningRequest(id);
                                objectData = awData;
                                html = RenderPartialView("_AircraftWarningLightDetail", awData);
                                break;
                            case (int)ServiceEnum.TradeLicenseRequest:
                                var tlData = userRequestService.GetTradeLicenseRequest(id, true);
                                objectData = tlData;
                                html = RenderPartialView("_TradeLicenseRequestDetail", tlData);
                                break;
                            case (int)ServiceEnum.MeteorologicalDataRequest:
                                var mrData = userRequestService.GetMeteorologicalDataRequest(id);
                                objectData = mrData;
                                html = RenderPartialView("_MeteorologicalDataRequest", mrData);
                                break;
                            case (int)ServiceEnum.ExitOfAircraftSparePartsRequest:

EService/EService.Web/Views/ServiceRequest/Description.cshtml
@model EService.Data.Entity.Entity.Service
@{
    /**/

    ViewBag.Title = @Model.ServiceName + " - Description";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@if (Model != null)
{
    <div class="row">
        <a href="@Url.Action("Index", "ServiceRequest", new { Area = "", serviceId = Model.ServiceId })" class="btn btn-warning">
            Proceed to Requests&nbsp; <i class="glyphicon glyphicon-step-forward"></i>
        </a>
    </div>
    <div class="row">&nbsp;</div>
    <div class="row">
        <h3>
            @Model.ServiceName
        </h3>
        <p>
            @Html.Raw(Model.Description)
        </p>

    </div>
    <div class="row">&nbsp;</div>
    <div class="row">
        <a href="@Url.Action("Index", "ServiceRequest", new { Area = "", serviceId = Model.ServiceId })" class="btn btn-warning">
            Proceed to Requests &nbsp;<i class="glyphicon glyphicon-step-forward"></i>
        </a>
    </div>
}

EService/EService.Web/Views/ServiceRequest/Detail.cshtml
@{
    ViewBag.Title = "User Service Requests";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row text-right" data-role="navigation-up" data-bind="template:{name: 'navTemplate'}"></div>
<div class="row" id="currentStatusContent" data-bind="template:{name: 'currentStatusTemplate'}"></div>
<div class="row" id="detailContent"></div>
<div class="row" id="uploadedFileContent" data-bind="template:{name: 'uploadedFileContentTemplate'}"></div>
<div class="row" id="historyContent" data-bind="template:{name: 'historyTemplate'}"></div>
<div class="row" id="paymentInfoContent" data-bind="template:{name: 'paymentInfoTemplate'}"></div>
<div class="row" id="receiptInfoContent" data-bind="template:{name: 'receiptInfoTemplate'}"></div>
<div class="row text-right" data-role="navigation-down" data-bind="template:{name: 'navTemplate'}">
</div>
<script type="text/html" id="navTemplate">
    <a href="javascript:void()" class="btn btn-warning" data-bind="attr:{href:'/ServiceRequest/Index?ServiceId='+ServiceId()}"><i class="fa fa-backward"></i>&nbsp; Back</a>
    <!-- ko if:Status() === fia.ServiceFlowStateEnum.Rejected -->
    <a class="btn btn-danger" href="javascript:void()" data-bind="attr:{href: '/ServiceRequest/Reapply?id='+UserServiceRequestMasterId()}"><i class="fa fa-repeat"></i>&nbsp; ReApply</a>
    <!--/ko-->
</script>
<script type="text/html" id="currentStatusTemplate">
    <!--ko with:ServiceInfo-->
    <fieldset>
        <legend>
            Service Info
        </legend>
        <dl class="dl-horizontal">
            <dt>Service Type</dt>
            <dd> <strong><span data-bind="text:ServiceName"></span></strong></dd>
        </dl>
        <dl class="dl-horizontal">
            <dt>Requested Date</dt>
            <dd> <strong><span data-bind="text:ServiceRequestDateTime"></span></strong></dd>
        </dl>
        <dl class="dl-horizontal">
            <dt>Current Status</dt>
            <dd> <strong><span data-bind="text:CurrentStatus"></span></strong></dd>
        </dl>

    </fieldset>
    <!--/ko-->
</script>
<script type="text/html" id="uploadedFileContentTemplate">
    <fieldset>
        <legend>Uploaded Files</legend>
        <!--ko if: UploadedFiles().length >0-->
        <ul style="list-style: none" data-bind="foreach: UploadedFiles">
            <li><span data-bind="text: FileName"></span></li>
        </ul>
        <!--/ko-->
        <!--ko ifnot: UploadedFiles().length >0-->
        <span><u><b>No Files uploaded for this request.</b></u></span>
        <!--/ko-->
    </fieldset>
</script>

<script type="text/html" id="historyTemplate">
    <table class="table table-bordered table-condensed">
        <thead>
            <tr>
                <th>Stage</th>
                <th> Department</th>
                <th> Changed By User</th>
                <th> Changed Status</th>
                <th> Changed Date Time</th>
                <th> Remarks</th>
            </tr>
        </thead>
        <tbody data-bind="foreach: History">
            <tr>
                <th data-bind="text: StageIndex"></th>
                <th data-bind="text: DepartmentName"></th>
                <th data-bind="text: DepartmentUserName"></th>
                <th data-bind="text: StatusName"></th>
                <th data-bind="text: moment(StatusChangedDateTime()).isValid() ? moment(StatusChangedDateTime()).format('DD/MM/YY hh:mm:ss a') : '' "></th>
                <th data-bind="text: Remarks "></th>
            </tr>
        </tbody>
        <tbody data-bind="if: History().length < 1">
            <tr>
                <td colspan="6">No History Yet</td>
            </tr>
        </tbody>
    </table>
</script>
<script type="text/html" id="paymentInfoTemplate">
    <!--ko with: PaymentInfo-->
    <!--ko if: IsPaymentStage-->
    <fieldset>
        <legend>
            Payment Info
        </legend>
        <h6>Your request for this service has been approved. Now you have to pay.</h6>
        <dl class="dl-horizontal">
            <dt>Service Charge</dt>
            <dd> <strong><span data-bind="text:ServiceCharge"></span></strong></dd>
        </dl>
        <a class="btn btn-warning" href="javascript:void()" data-bind="click: function(){$root.ProceedToPaymentClick($root.UserServiceRequestMasterId());}"><i class="fa fa-money"></i>&nbsp; Proceed to Payment</a>


    </fieldset>
    <!--/ko-->
    <!--/ko-->

 
</script>
<script type="text/html" id="receiptInfoTemplate">
    <!--ko with: PaymentInfo-->
    <!--ko if: HasReceipts-->
    <fieldset>
        <legend>
            Payment Info
        </legend>
        <h6>Your payment has been completed. You can print your receipt here.</h6>
        @*<table class="table table-bordered">

                <thead>
                    <tr>
                        <th>S.No.</th>
                        <th>Receipt No</th>
                        <th>Reg No</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody data-bind="foreach: Receipts">
                    <tr>
                        <td></td>
                        <td><span data-bind="text:ReceiptNo"></span></td>
                        <td><span data-bind="text:RequestRegistrationNo"></span></td>
                        <td>
                            <a class="btn btn-warning" href="javascript:void()" data-bind="click: function(){$root.DownloadReceiptList(ReceiptId());}"><i class="fa fa-download"></i>&nbsp; Download Receipt</a>
                        </td>
                    </tr>
                </tbody>
            </table>*@

        <a class="btn btn-warning" href="javascript:void()" data-bind="click: function(){$root.GotoReceiptList($root.UserServiceRequestMasterId());}"><i class="fa fa-money"></i>&nbsp; Proceed to Receipt</a>


    </fieldset>
    <!--/ko-->
    <!--/ko-->
</script>
@section scripts{
    @Html.Partial("_Scripts")
    <script type="text/javascript">
        $(function () {
            fia.serviceRequest.InitializeDetail();
        })
    </script>
}

EService/EService.Web/Views/ServiceRequest/DownloadReceipt.cshtml
@using EService.Service.Model
@model ResponseObject<ReceiptPrintModel>
@{
    ViewBag.Title = "DownloadReceipt";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section scripts{

    @*<script src="~/Scripts/jspdf/es6-promise.auto.min.js"></script>
    <script src="~/Scripts/jspdf/jspdf.min.js"></script>
    <script src="~/Scripts/jspdf/html2canvas.min.js"></script>
    <script src="~/Scripts/jspdf/html2pdf.min.js"></script>*@
    <script src="https://unpkg.com/jspdf@latest/dist/jspdf.min.js"></script>
    <script type="text/javascript">
        var doc = new jsPDF();

        // We'll make our own renderer to skip this editor
        var specialElementHandlers = {
            '#editor': function (element, renderer) {
                return true;
            },
            '.controls': function (element, renderer) {
                return true;
            }
        };
        $(function () {
            // All units are in the set measurement for the document
            // This can be changed to "pt" (points), "mm" (Default), "cm", "in"
            doc.fromHTML($('#receipt').get(0), 15, 15, {
                'width': 340,
                'elementHandlers': specialElementHandlers
            });
            doc.save('Receipt.pdf');
        })
       
    </script>

}

@if (Model.IsSuccess)
{
    <div class="col-xs-8">
        @Html.Partial("_ReceiptFormat", Model.Data)
    </div>
}
else
{
    <span class="alert alert-danger">
        Error
    </span>
}

EService/EService.Web/Views/ServiceRequest/Index.cshtml
@{
    ViewBag.Title = "User Service Requests";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div id="mainContent" class="form-horizontal" data-bind="template:{name: 'listContentTemplate'}">
</div>
<script type="text/html" id="listContentTemplate">
    <fieldset>
        <legend>
            Search Options
        </legend>
        <div class="col-xs-12" data-bind="with: SearchModel">
            <div class="col-xs-12 col-sm-6 col-md-4">
                <input type="text" class="form-control" data-bind="datePicker: DateFrom" placeholder="Date From" />
            </div>
            <div class="col-xs-12 col-sm-6 col-md-4">
                <input type="text" class="form-control" data-bind="datePicker: DateTo" placeholder="Date To" />
            </div>
            <div class="col-xs-12 col-sm-6 col-md-4">
                <select name="ServiceStatus" class="form-control" data-bind="value: ServiceStatus,options: ServiceStatusList, optionsText: 'Description', optionsValue: 'Id', optionsCaption: 'Select Service Status' "></select>
            </div>
            <div class="col-xs-12 col-sm-6 col-md-4">
            </div>
            <div class="col-xs-12 col-sm-6 col-md-4">
            </div>
            <div class="col-xs-12 col-sm-6 col-md-4">
                <br />
                <button type="button" class="btn btn-primary ladda-button" data-role="search" data-style="expand-left" data-bind="click: $parent.SearchClick">Search</button>
            </div>
        </div>
    </fieldset>

    <h4 data-bind="text: ServiceName"></h4>
    <div class="col-xs-12 text-right">
        <a href="@Url.Action("Create")" class="btn btn-primary"> <i class="fa fa-plus"></i> &nbsp;New Request</a>
    </div>
    <div class="col-xs-12 table-responsive">
        <table class="table table-bordered table-condensed table-striped">
            <thead>
                <tr>
                    <th>NOC Req Ref No </th>
                    <th>Request Type</th>
                    <th>User (Email)</th>
                    <th>Requested Date Time</th>
                    <th>Service Status</th>
                    <th>Request Status</th>
                    <th></th>
                </tr>
            </thead>
            <tbody data-bind="foreach: Records">
                <tr>
                    <td data-bind="text: RegistrationNo"></td>
                    <td data-bind="text: IsReapplied() ? 'Reapplied':'New' "></td>
                    <td data-bind="text: UserName()+'( '+Email()+' )' "></td>
                    <td data-bind="text: moment(RequestDateTime()).format('DD/MM/YY hh:mm:ss a')"></td>
                    <td data-bind="text: IsDraft() === true ? 'Draft' : 'Submitted' "></td>
                    <td data-bind="text: RequestStatusName"></td>
                    <td>
                        <a href="javascript:void(0)" data-bind="click:$root.ViewDetails" class="" title="View Detail"><i class="fa fa-eye"></i></a>
                        <!--ko if:IsDraft-->
                        <a href="javascript:void(0)" data-bind="click:$root.Edit" class="" title="Edit"><i class="fa fa-pencil"></i></a>
                        <!--/ko-->
                    </td>
                </tr>
            </tbody>
        </table>
    </div>

</script>
<script type="text/html" id="listSearchResultTemplate">
</script>
@section scripts{
    @Html.Partial("_Scripts")
    <script type="text/javascript">
        $(function () {
            fia.serviceRequest.Initialize();
        })
    </script>
}

EService/EService.Web/Views/ServiceRequest/Receipt.cshtml
@model List<EService.Service.Model.ReceiptPrintModel>
@{
    ViewBag.Title = "Receipt";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var index = 1;
}

<h2>Receipt</h2>
<table class="table table-bordered">

    <thead>
        <tr>
            <th>S.No.</th>
            <th>Receipt No</th>
            <th>Reg No</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@index</td>
                <td>@item.ReceiptNo</td>
                <td>@item.RequestRegistrationNo</td>
                <td>@Html.ActionLink("Download Receipt","DownloadReceipt", new { receiptid = item.ReceiptId })</td>
            </tr>
            index++;
        }
    </tbody>
</table>

EService/EService.Web/Views/ServiceRequest/_Scripts.cshtml
<script type="text/javascript" src="~/Scripts/fia/fia.serviceRequest.js"></script>