EService/EService.Web/Controllers/RegisterController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EService.Core.Security;
using EService.Data.Entity;
using EService.Data.Entity.Entity;
using EService.Service.Logic;
using EService.Service.Model;
using EService.Web.Helper;
using EService.Web.Models;

namespace EService.Web.Controllers
{
    public class RegisterController : Controller
    {
        private LookupService lookupService;
        private UserService userService;
        private ServiceContext serviceContext;
        private EmailService emailService;
        public RegisterController()
        {
            serviceContext = new ServiceContext();
            lookupService = new LookupService();
            userService = new UserService(context: serviceContext);
            emailService = new EmailService(serviceContext);
        }

        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public JsonResult Create(UserRegisterViewModel model)
        {
            var result = new JsonResponseObject();
            try
            {
                if (ModelState.IsValid)
                {
                    var password = model.PasswordHash;
                    model.PasswordHash = model.PasswordHash.ToMd5();
                    User user;
                    string message = "";
                    var saveResult = userService.RegisterUser(model, out user, out message);
                    if (saveResult)
                    {
                        result.IsSuccess = true;
                        result.Message = "User Registered Successfully.";
                        //send email

                        var emailModel = new NewRegistrationEmailModel()
                        {
                            UserName = model.UserName,
                            FullName = model.FirstName + " "+ model.LastName,
                            Password = password
                        };
                        var smtpSetting = emailService.Find(o => true);
                        var content = RenderPartialView("~/Views/Shared/EmailTemplates/_NewRegistrationEmailTemplate.cshtml", emailModel);
                        EmailHelper.SendEmail(smtpSetting.From, new string[] { model.Email }, new string[] { }, new string[] { }, "Successful Registration", content, smtpSetting);
                    }
                    else
                    {
                        result.IsSuccess = false;
                        result.Message = message;
                    }
                }
                else
                {
                    result.IsSuccess = false;
                    result.Message = ModelState.GetModelStateError();
                }
            }
            catch (Exception ex)
            {
                //LogError(ex);
                result.IsSuccess = false;
                result.Message = "Error while registering for the user.";
            }
            return Json(result);
        }

        public JsonResult Initialize()
        {
            var result = new JsonResponseObject();
            try
            {
                var model = new UserRegisterViewModel()
                {
                    SecurityQuestions = lookupService.GetList<SecurityQuestion>().ToList(),
                    CompanyCategories = lookupService.GetList<CompanyCategory>().ToList(),
                    Countries = CountryHelper.GetListOfCountries().Select(o=> new  LookupItem{ Description= o }).ToList()
                };

                result.Data = model;
                result.IsSuccess = true;
            }
            catch (Exception ex)
            {
                result.IsSuccess = false;
                result.Message = "Error while obtaining model: " + ex.Message;
            }

            return Json(result, JsonRequestBehavior.AllowGet);
        }


        protected virtual string RenderPartialView(string partialViewName, object model = null)
        {
            if (ControllerContext == null)
                return string.Empty;

            if (string.IsNullOrEmpty(partialViewName))
                throw new ArgumentNullException("partialViewName");

            ModelState.Clear();//Remove possible model binding error.

            ViewData.Model = model;//Set the model to the partial view

            using (var sw = new StringWriter())
            {
                var viewResult = ViewEngines.Engines.FindPartialView(ControllerContext, partialViewName);
                var viewContext = new ViewContext(ControllerContext, viewResult.View, ViewData, TempData, sw);
                viewResult.View.Render(viewContext, sw);
                return sw.GetStringBuilder().ToString();
            }
        }
    }
}

EService/EService.Web/Views/Register/Index.cshtml
@using EService.Web.App_GlobalResources
@using EService.Web.App_LocalResources
@model  EService.Web.Models.UserRegisterViewModel

@{
    ViewBag.Title = "User Register";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section scripts
{
    <script type="text/javascript" src="~/Scripts/fia/fia.register.js"></script>
    <script type="text/javascript">
        var isCaptchaVerified = false;
        var onloadCallback = function () {
            console.log('onloadcallback')
            grecaptcha.render('captcha', {
                'sitekey': '6LdguzIUAAAAAK4KwoJLQ4IKEBVYryegP6XpLglo',
                'callback': verifyCallback,
                'expired-callback': expiredCallback,
                'theme': 'light'
            });

        };

        var verifyCallback = function () {
            isCaptchaVerified = true;
        };
        var expiredCallback = function () {
            isCaptchaVerified = false;
        };


        $(function () {
          
            fia.register.Initialize();
        });
    </script>
}
<div id="mainContent" data-bind="template:{name: 'registerContent', afterRender: RenderComplete}">
    
</div>

<script type="text/html" id="registerContent">
    <h4>Customer Registration</h4>
    @using (Html.BeginForm("Create", "Register", FormMethod.Post, new { id = "userRegisterForm", @class = "form-horizontal", data_bind = "with:AddModel" }))
    {
        <fieldset>
            <legend>
                @Register.AccountDetail
            </legend>
            <div class="form-group">
                <div class="col-sm-4 control-label">
                    @Html.LabelFor(model => model.FirstName, Register.FirstName)
                    <span class="red">*</span>
                </div>
                <div class="col-sm-8">
                    @Html.TextBoxFor(model => model.FirstName, new { @class = "form-control", data_bind = "value:FirstName", placeholder = "First Name" })
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-4 control-label">
                    @Html.LabelFor(model => model.LastName, Register.LastName)
                    <span class="red">*</span>
                </div>
                <div class="col-sm-8">
                    @Html.TextBoxFor(model => model.LastName, new { @class = "form-control", data_bind = "value:LastName", placeholder = "Last Name" })
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-4 control-label">
                    @Html.LabelFor(model => model.UserName, Register.UserName)
                    <span class="red">*</span>
                </div>
                <div class="col-sm-8">
                    @Html.TextBoxFor(model => model.UserName, new { @class = "form-control", data_bind = "value:UserName", placeholder = "User Name" })
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-4 control-label">
                    @Html.LabelFor(model => model.PasswordHash, Register.Password)
                    <span class="red">*</span>
                </div>
                <div class="col-sm-8">
                    @Html.PasswordFor(model => model.PasswordHash, new { @class = "form-control", data_bind = "value:PasswordHash", placeholder = "Password" })
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-4 control-label">
                    @Html.LabelFor(model => model.ConfirmPassword, Register.ConfirmPassword)
                    <span class="red">*</span>
                </div>
                <div class="col-sm-8">
                    @Html.PasswordFor(model => model.ConfirmPassword, new { @class = "form-control", data_bind = "value:ConfirmPassword", placeholder = "Confirm Password" })
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-4 control-label">
                    @Html.LabelFor(model => model.Email, Register.Email)
                    <span class="red">*</span>
                </div>
                <div class="col-sm-8">
                    @Html.TextBoxFor(model => model.Email, new { @class = "form-control", data_bind = "value:Email", placeholder = "Enter email here [email@domain.com]" })
                </div>
            </div>
        </fieldset>
        <fieldset>
            <legend>
                @Register.ContactPersonDetails
            </legend>
            <div class="form-group">
                <div class="col-sm-4 control-label">
                    @Html.LabelFor(model => model.ContactPersonName, Register.ContactPerson)
                </div>
                <div class="col-sm-8">
                    @Html.TextBoxFor(model => model.ContactPersonName, new { @class = "form-control", data_bind = "value:ContactPersonName", placeholder = "Enter Name here" })
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-4 control-label">
                    @Html.LabelFor(model => model.ContactPersonMobile, Register.Mobile)
                </div>
                <div class="col-sm-8">
                    @Html.TextBoxFor(model => model.ContactPersonMobile, new { @class = "form-control", data_bind = "value:ContactPersonMobile", placeholder = "Enter mobile number here" })
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-4 control-label">
                    @Html.LabelFor(model => model.EmiratesId, Register.EmiratesId)
                </div>
                <div class="col-sm-8">
                    @Html.TextBoxFor(model => model.EmiratesId, new { @class = "form-control", data_bind = "value:EmiratesId", placeholder = "Enter Emirates ID here" })
                </div>
            </div>

        </fieldset>
        <fieldset>
            <legend>
                @Register.CompanyDetails
            </legend>
            <div class="form-group">
                <div class="col-sm-4 control-label">
                    @Html.LabelFor(model => model.CompanyCategoryId, Register.Category)
                    <span class="red">*</span>
                </div>
                <div class="col-sm-8">
                    @*CompanyCategories*@
                    @Html.DropDownListFor(model => model.CompanyCategoryId, new SelectList(Enumerable.Empty<int>()), Register.CategorySelect, new { @class = "form-control", data_bind = "value:CompanyCategoryId, options:CompanyCategories, optionsText:'Description', optionsValue:'Id', optionsCaption:'Select' ", placeholder = "Enter Name here" })
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-4 control-label">
                    @Html.LabelFor(model => model.CompanyName, Register.CompanyName)
                </div>
                <div class="col-sm-8">
                    @Html.TextBoxFor(model => model.CompanyName, new { @class = "form-control", data_bind = "value:CompanyName", placeholder = "Enter company name here" })
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-4 control-label">
                    @Html.LabelFor(model => model.CompanyAddress, Register.CompanyAddress)
                </div>
                <div class="col-sm-8">
                    @Html.TextAreaFor(model => model.CompanyAddress, new { @class = "form-control width100", data_bind = "value:CompanyAddress", placeholder = "Enter Company Address here" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Phone, Register.Phone, new { @class = "col-sm-4 control-label" })
                <div class="col-sm-8">
                    @Html.TextBoxFor(model => model.Phone, new { @class = "form-control", data_bind = "value:Phone", placeholder = "Enter phone number here" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Fax, Register.Fax, new { @class = "col-sm-4 control-label" })
                <div class="col-sm-8">
                    @Html.TextBoxFor(model => model.Fax, new { @class = "form-control", data_bind = "value:Fax", placeholder = "Enter fax number here" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.POBox, Register.POBox, new { @class = "col-sm-4 control-label" })
                <div class="col-sm-8">
                    @Html.TextBoxFor(model => model.POBox, new { @class = "form-control", data_bind = "value:POBox", placeholder = "Enter P.O. Box here" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.City, Register.City, new { @class = "col-sm-4 control-label" })
                <div class="col-sm-8">
                    @Html.TextBoxFor(model => model.City, new { @class = "form-control", data_bind = "value:City", placeholder = "Enter City here" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Country, Register.Country, new { @class = "col-sm-4 control-label" })
                <div class="col-sm-8">
                    @Html.DropDownListFor(model => model.Country, new List<SelectListItem>(), new { @class = "form-control", data_bind = "value:Country, options: Countries, optionsText:'Description', optionsValue:'Description', optionsCaption:'Select your country' ", placeholder = "Enter Country here" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.VATRegistrationNo, Register.VATRegistrationNo, new { @class = "col-sm-4 control-label" })
                <div class="col-sm-8">
                    @Html.TextBoxFor(model => model.VATRegistrationNo, new { @class = "form-control", data_bind = "value:VATRegistrationNo", placeholder = "Enter VAT RegistrationNo here" })
                </div>
            </div>
        </fieldset>
        <fieldset>
            <legend>
                @Register.SecurityDetails
            </legend>
            <div class="form-group">
                <div class="col-sm-4 control-label">
                    @Html.LabelFor(model => model.SecurityQuestionId, Register.Question)
                    <span class="red">*</span>
                </div>
                <div class="col-sm-8">
                    @Html.DropDownListFor(model => model.SecurityQuestionId, new SelectList(Enumerable.Empty<int>()), Register.CategorySelect, new { @class = "form-control", data_bind = "value:SecurityQuestionId, options:SecurityQuestions, optionsText:'Description', optionsValue:'Id', optionsCaption:'Select' ", placeholder = "Enter Name here" })
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-4 control-label">
                    @Html.LabelFor(model => model.Answer, Register.Answer)
                    <span class="red">*</span>
                </div>
                <div class="col-sm-8">
                    @Html.TextBoxFor(model => model.Answer, new { @class = "form-control", data_bind = "value:Answer" })
                </div>
            </div>
        </fieldset>
        <hr />
        <div class="form-group">
            <div class="col-sm-2">
                <div class="control-label">
                </div>
            </div>
            <div class="col-sm-8">
                <div id="captcha" class="g-recaptcha" data-sitekey="6LdguzIUAAAAAK4KwoJLQ4IKEBVYryegP6XpLglo"></div>
            </div>
        </div>
        <hr />
        <div class="form-group">
            <div class="col-sm-offset-4 col-sm-8">
                <button class="btn btn-primary ladda-button" data-style="expand-left" type="button" id="btnRegister" data-bind="click: $parent.Save"><span class="ladda-label">@GlobalResource.Submit</span></button>
            </div>
        </div>
    }
</script>